### ISSUE TITLE
peer dependency mismatch

### ISSUE THREAD

**Issue by hyperknot** [ory/integrations#46]
Why is @ory/client specified both as a dependency and as a peerDependency? Not just that, but they have conflicting versions.

https://github.com/ory/integrations/blob/84858eafd718cc28682ca4cc2d713e86b0b36de8/package.json#L40-L45

**Comment by aeneasr** [comment]
That's definitely a mistake, thank you!

https://github.com/ory/integrations/pull/48

**Comment by Jtango18** [comment]
When is this likely to be published?
