### ISSUE TITLE
Upgrade actions to node 18

### ISSUE THREAD

**Issue by dan-j** [ory/integrations#62]
The release triggered as per the discussion in https://github.com/ory/integrations/issues/51 failed because the version of node in the GitHub Actions `release` workflow is older than what next requires.

The tests pass locally when upgrading to node v18.19.1, so I suggest we upgrade actions as such.

Additionally, the `test` workflow is already configured to run using v18 and v20, so this shouldn't be an issue from a compatibility perspective.

**Comment by dan-j** [comment]
@aeneasr are you able to trigger a new release since the above was merged? Happy to close this once that's addressed.

**Comment by aeneasr** [comment]
Thank you for the reminder, done!
